### ISSUE TITLE
Simple example doesn't work as intended

### ISSUE THREAD

**Issue by mlarchet** [dell/terraform-provider-powerstore#110]
I'm trying to add a new volume to an existing volume group.
Can't figure why host_group data returns a list instead of the specific object I request through its name.

```
data "powerstore_hostgroup" "hostgroup" {
  name = "my-hostgroup"
}

resource "powerstore_volume" "volume" {
  name = "my-volume"
  size = 500
  host_group_id = data.powerstore_hostgroup.hostgroup.id
}
```

This leads to the following error :
`Could not create volume, unexpected error: The host group id placeholder is not valid for the attach or detach operation on volume`

What am I doing wrong ? Why a data lookup for a specific object returns a list ?

**Comment by anupamaloke** [comment]
@mlarchet , could you please share the PowerStore OS version details?

**Comment by doriac11** [comment]
@mlarchet yes the name is filtering on the list of powerstores.

I think you could access the specific host id like so
```
data "powerstore_hostgroup" "hostgroup" {
  name = "my-hostgroup"
}

resource "powerstore_volume" "volume" {
  name = "my-volume"
  size = 500
  host_group_id = data.powerstore_hostgroup.hostgroup[0].id
}
```

that way it will take the first instance of the host group datasource.
